/* Support for bitmap fonts generated by https://github.com/achilikin/bdfe

   Copyright (c) 2015 Andrey Chilikin (https://github.com/achilikin)

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef BITMAP_FONT_H
#define BITMAP_FONT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#if 0
} // dummy bracket for Visual Assist
#endif
#endif

#define BMFONT_6x8  0
#define BMFONT_8x8  1
#define BMFONT_8x16 2
#define BMFONT_USER 3
#define BMFONT_MAX  BMFONT_USER

typedef struct bmfont_s
{
	uint8_t gw; /*< glyph width  */
	uint8_t gh; /*< glyph height */
	uint8_t go; /*< font offset, first glyph index */
	uint8_t gn; /*< number of glyphs presented */
	const uint8_t *font;
} bmfont_t;

/** text attributes */
#define TEXT_REVERSE   0x01
#define TEXT_UNDERLINE 0x02
#define TEXT_OVERLINE  0x04

/** select one of three fonts for following text drawing calls */
uint8_t bmfont_select(uint8_t font);

/** get currently selected font */
bmfont_t *bmfont_get(void);

/** 
 set user font selectable by BMFONT_USER to nfont
 store current user font in ofont (if not NULL)
 */
void bmfont_set(bmfont_t *nfont, bmfont_t *ofont);

#ifdef __cplusplus
}
#endif

#endif
