/* Support for bitmap fonts generated by https://github.com/achilikin/bdfe

   Copyright (c) 2015 Andrey Chilikin (https://github.com/achilikin)

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include <stdio.h>
#ifdef __AVR_ARCH__
	#include <avr/pgmspace.h>
#else
	#define PROGMEM
#endif

#include "bmfont.h"

static const uint8_t font68[] PROGMEM = {
#include "font6x8.h"
};

static const uint8_t font88[] PROGMEM = {
#include "font88.h"
};

static const uint8_t font816[] PROGMEM = {
#include "font816.h"
};

static bmfont_t _ofont[BMFONT_MAX+1] = {
	{  6,  8, 32, 127-32, font68 },	
	{  8,  8, 32, 127-32, font88 },
	{  8, 16, 32, 127-32, font816 },
	{  0,  0, 0,       0, NULL }
};

static uint8_t _cfont;

uint8_t bmfont_select(uint8_t font)
{
	uint8_t fret = _cfont;
	if (font <= BMFONT_MAX)
		_cfont = font;
	return fret;
}

bmfont_t *bmfont_get(void)
{
	return &_ofont[_cfont];
}

void bmfont_set(bmfont_t *nfont, bmfont_t *ofont)
{
	if (ofont) {
		ofont->gw = _ofont[BMFONT_USER].gw;
		ofont->gh = _ofont[BMFONT_USER].gh;
		ofont->go = _ofont[BMFONT_USER].go;
		ofont->gn = _ofont[BMFONT_USER].gn;
		ofont->font = _ofont[BMFONT_USER].font;
	}
	_ofont[BMFONT_USER].gw = nfont->gw;
	_ofont[BMFONT_USER].gh = nfont->gh; 
	_ofont[BMFONT_USER].go = nfont->go;
	_ofont[BMFONT_USER].gn = nfont->gn;
	_ofont[BMFONT_USER].font = nfont->font;
}
